---
- name: playbook_fish.yml - fish!
  hosts: all

  tasks:
    - name: install base fish and curl
      become: yes
      pacman:
        update_cache: yes
        name:
          - fish
          - curl
          - starship
          - ttf-jetbrains-mono-nerd
    
    - name: change shell
      become: yes
      user:
        name: "{{ ansible_user }}"
        shell: /bin/fish

    # SETUP SHELL AND CONFIGS
    - name: copy config directory with prefernces, hotkeys, syntax highlight
      become: no
      copy:
        src: .config/fish
        dest: ~/.config
        mode: preserve

    - name: set starship configuration
      become: no
      command: starship preset pastel-powerline -o ~/.config/starship.toml
    
    # - name: ensure /root/.config exists
    #   file:
    #     path: /root/.config
    #     state: directory
    #     mode: '0755'

    # - name: remove root fish config if it exists
    #   file:
    #     path: /root/.config/fish
    #     state: absent

    # - name: symlink users fish config for the root, so that it works in sudo
    #   file:
    #     src: "/home/{{ ansible_user }}/.config/fish"
    #     dest: /root/.config/fish
    #     state: link
    #     force: yes
    #     follow: false