---
- name: playbook_docker.yml - docker and stuff
  hosts: all
  become: yes

  tasks:
    - name: install docker and docker compose and ctop
      pacman:
        update_cache: yes
        name:
          - docker
          - docker-compose
          - ctop

    - name: enable and start docker.service
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: add the user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Create /etc/docker directory if it does not exist
      file:
        path: /etc/docker
        state: directory
        mode: '0755'

    - name: daemon.json, sets max logs size, and prevent docker network getting in to 192.168.0.0
      copy:
        dest: '/etc/docker/daemon.json'
        content: |
          {
            "log-driver": "json-file",
            "log-opts": {
              "max-size": "50m",
              "max-file": "5"
            },
            "default-address-pools": [
              {
                "base" : "172.16.0.0/12",
                "size" : 24
              }
            ]
          }

    - name: move docker compose files
      become: no
      copy:
        src: docker/portainer_compose.yml
        dest: /tank/docker
        mode: preserve

    - name: Ensure portainer_compose.yml exists
      stat:
        path: /tank/docker/portainer_compose.yml
      register: compose_file
      
    - name: Fail if compose file doesn't exist
      fail:
        msg: "portainer_compose.yml not found in /tank/docker/"
      when: not compose_file.stat.exists
      
    - name: Start Portainer with docker compose
      shell: docker compose up -d -f portainer_compose.yml
      args:
        chdir: /tank/docker
      register: compose_result
      
    - name: Display compose result
      debug:
        var: compose_result.stdout_lines