networks:
  traefik_internal:
    name: traefik-internal
    external: true

services:
  whoami:
    image: traefik/whoami
    labels:
      - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)"